_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: 7e1979fd-46e0-4941-a795-23db91f8b5f6
name: 'Food Truck Navigator'
mail: freenjt@gmail.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/470
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
